JOB START DT : '2018-10-23 05:23:40' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 05:23:48' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 05:23:40' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 05:23:48' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: ORA-00904: "VALUE_ADD_PARTNER_NAGP": invalid identifier
JOB START DT : '2018-10-23 05:25:51' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 05:25:58' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 05:25:51' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 05:25:58' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: ORA-00904: "VALUE_ADD_PARTNER_NAGP": invalid identifier
JOB START DT : '2018-10-23 06:02:01' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 06:02:08' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 06:02:01' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 06:02:08' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: ORA-06550: line 168, column 13:
PL/SQL: ORA-00933: SQL command not properly ended
ORA-06550: line 3, column 5:
PL/SQL: SQL Statement ignored
ORA-06550: line 168, column 16:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   ;
JOB START DT : '2018-10-23 06:04:57' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 06:05:05' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 06:04:57' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 06:05:05' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: ORA-06550: line 168, column 16:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
JOB START DT : '2018-10-23 08:57:53' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 08:57:57' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 08:57:53' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 08:57:57' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: 'DataFrame' object has no attribute 'collectAsList'
JOB START DT : '2018-10-23 09:09:04' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:09:08' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 09:09:04' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:09:08' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: 'DataFrame' object has no attribute 'flatMap'
JOB START DT : '2018-10-23 09:12:44' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:12:50' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 09:12:44' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:12:50' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: mvv
JOB START DT : '2018-10-23 09:15:11' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:15:17' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 09:15:11' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:15:17' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: mvv
JOB START DT : '2018-10-23 09:47:59' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:49:46' | STATUS : Success
JOB START DT : '2018-10-23 09:55:30' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 09:57:38' | STATUS : Success
JOB START DT : '2018-10-23 10:34:53' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 10:34:55' | STATUS : [Error] Failed
JOB START DT : '2018-10-23 10:34:53' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 10:34:55' | STATUS : 
 __main__ JB_WORK_INVOICE_DATAPREP --> Exception-Traceback :: name 'schema' is not defined
JOB START DT : '2018-10-23 10:36:07' | SCRIPT NAME : SCH1100.py | JOB : JB_WORK_INVOICE_DATAPREP | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-23 10:37:34' | STATUS : Success
